app = "boc-saleor-apps"
primary_region = "bom"
kill_signal = "SIGINT"
kill_timeout = 5

[build]
  dockerfile = "Dockerfile"

[build.args]
  PROJECT="smtp"

[http_service]
  internal_port = 8081
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

  [[http_service.checks]]
    grace_period = "10s"
    interval = "1m0s"
    method = "GET"
    path = "/healthcheck/"
    timeout = "1s"

  # [http_service.checks]
  #   [http_service.checks.health]
  #     grace_period = "10s"
  #     interval = "30s"
  #     method = "GET"
  #     path = "/health"
  #     timeout = "5s"


[[vm]]
  cpu_kind = "shared"
  cpus = 2
  memory_mb = 1024
